In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [3]:
import pandas as pd
data=pd.read_csv('data.csv', on_bad_lines='skip')
data.head()



password  strength
0     kzde5577       1.0
1     kino3434       1.0
2    visi7k1yr       1.0
3     megzy123       1.0
4  lamborghin1       1.0

In [4]:
data['strength'].unique()

array([ 1.,  2.,  0., nan])

In [5]:
data[data['password'].isnull()]

password  strength
367579      NaN       0.0

In [6]:
password_tuple=np.array(data)
password_tuple

array([['kzde5577', 1.0],
       ['kino3434', 1.0],
       ['visi7k1yr', 1.0],
       ...,
       ['viniabde2', 1.0],
       ['rangaj777', 1.0],
       ['fd8D', nan]], dtype=object)

In [7]:
import random
random.shuffle(password_tuple)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
def word_divide_char(inputs):
    character=[]
    for i in inputs:
        character.append(i)
    return character

x=[labels[0] for labels in password_tuple]
y=[labels[1] for labels in password_tuple]


vectorizer=TfidfVectorizer(tokenizer=word_divide_char)  #Converts a collection of raw documents to a matrix of TF-IDF features.
X=vectorizer.fit_transform(x)
X.shape
vectorizer.get_feature_names_out()

/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array(['\x05', '\x06', '\x08', '\x10', '\x16', '\x17', '\x19', '\x1b',
       '\x1c', '\x1e', ' ', '!', '"', '#', '$', '%', '&', '(', ')', '*',
       '+', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`',
       'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
       '{', '|', '}', '~', '\x7f', '\x8d', '\xa0', '¡', '¨', '«', '°',
       '±', '²', '³', '´', 'µ', '·', 'º', '¾', '¿', 'ß', 'à', 'á', 'â',
       'ä', 'å', 'æ', 'ç', 'è', 'é', 'ê', 'í', 'ï', 'ð', 'ñ', 'ò', 'ó',
       'ô', 'õ', '÷', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'ÿ', 'œ', '—', '‚',
       '…', '‹', '›'], dtype=object)

In [9]:
first_document_vector=X[0]
first_document_vector
first_document_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56709861],
        [0.        ],
        [0.59119028],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [10]:
df=pd.DataFrame(first_document_vector.T.todense(),index=vectorizer.get_feature_names_out(),columns=['TF-IDF'])
df.sort_values(by=['TF-IDF'],ascending=False)

TF-IDF
7   0.591190
5   0.567099
z   0.336178
k   0.292163
d   0.285683
..       ...
>   0.000000
=   0.000000
<   0.000000
;   0.000000
›   0.000000

[125 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)
X_train.shape

(451241, 125)

In [12]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0,multi_class='multinomial')
clf.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(multi_class='multinomial', random_state=0)

In [13]:
y_pred=clf.predict(X_test)
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

In [14]:
dt=np.array(['amar'])
pred=vectorizer.transform(dt)
clf.predict(pred)

array([0.])

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[ 4584 10568    13]
 [ 3377 78176  2078]
 [   41  4261  9713]]
0.8197161624309686


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.57      0.30      0.40     15165
         1.0       0.84      0.93      0.89     83631
         2.0       0.82      0.69      0.75     14015

    accuracy                           0.82    112811
   macro avg       0.75      0.64      0.68    112811
weighted avg       0.80      0.82      0.80    112811



In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
dtc=DecisionTreeClassifier(random_state=0)
dtc.fit(X_train,y_train)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.57      0.30      0.40     15165
         1.0       0.84      0.93      0.89     83631
         2.0       0.82      0.69      0.75     14015

    accuracy                           0.82    112811
   macro avg       0.75      0.64      0.68    112811
weighted avg       0.80      0.82      0.80    112811

